version: "3.8"

services:
  oracledb:
    image: "gvenzl/oracle-xe:18-faststart"
    restart: always
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    ports:
      - "1521:1521"
    expose:
      - "1521"