CREATE TABLE CAR
(
    ID INT,
    NAME VARCHAR2(255) NOT NULL,
    COLOR VARCHAR2(255) NOT NULL,
    YEAR INT NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE CAR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER CAR_TRIGGER
    BEFORE INSERT ON CAR FOR EACH ROW
BEGIN
    SELECT CAR_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
